In [1]:
import numpy as np

# Generate random arrays

In [2]:
x1 = np.random.random((5,3))
x1

array([[0.82700365, 0.0068228 , 0.15273367],
       [0.87085495, 0.34633178, 0.79214699],
       [0.30725323, 0.86123822, 0.62532371],
       [0.4430441 , 0.0030345 , 0.32700724],
       [0.98949381, 0.37325568, 0.06059556]])

In [3]:
x2 = np.random.randint(1000, size=30)
x2

array([235,  81,  83, 610, 373, 622, 982, 451,  84, 475, 296, 457, 787,
       416, 964, 997, 445, 779, 131, 669,  95,  46,   5, 642, 374, 460,
       723, 848, 365, 581])

In [4]:
x3 = np.random.randint(10, size=(2, 3, 4))
x3

array([[[9, 1, 4, 7],
        [2, 7, 7, 6],
        [0, 5, 6, 0]],

       [[8, 7, 1, 5],
        [9, 5, 3, 4],
        [8, 5, 9, 4]]])

### Print ndim, shape and size

In [5]:
print('x1 ndim:', x1.ndim, '| shape', x1.shape, '| size', x1.size)
print('x2 ndim:', x2.ndim, '| shape', x2.shape, '| size', x2.size)
print('x3 ndim:', x3.ndim, '| shape', x3.shape, '| size', x3.size)

x1 ndim: 2 | shape (5, 3) | size 15
x2 ndim: 1 | shape (30,) | size 30
x3 ndim: 3 | shape (2, 3, 4) | size 24


### Print itemsize and nbytes

In [6]:
print("itemsize:", x1.itemsize, "bytes")
print("itemsize:", x2.itemsize, "bytes")
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")
print("nbytes:", x2.nbytes, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
itemsize: 8 bytes
itemsize: 8 bytes
nbytes: 120 bytes
nbytes: 240 bytes
nbytes: 192 bytes


# Array Indexing

In [7]:
x = np.random.randint(10, size=5)
x

array([0, 0, 9, 3, 8])

In [8]:
x[1]

0

In [9]:
x[-1]

8

In [10]:
y = np.random.randint(10, size=(3, 4))
y

array([[5, 3, 3, 0],
       [8, 6, 5, 2],
       [5, 7, 6, 2]])

In [11]:
y[2, 0]

5

In [12]:
y[2, -2]

6

# Array Slicing

### One-dimensional subarrays

In [13]:
# x[start:stop:step]

In [14]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
x[:5]

array([0, 1, 2, 3, 4])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
x[1::2]

array([1, 3, 5, 7, 9])

### Multi-dimensional subarrays

In [19]:
x4 = np.random.randint(10, size=(2, 4, 5))
x4

array([[[7, 1, 8, 1, 7],
        [6, 8, 5, 0, 8],
        [0, 5, 6, 3, 1],
        [3, 5, 0, 6, 4]],

       [[0, 1, 1, 5, 8],
        [8, 5, 2, 3, 5],
        [9, 0, 9, 1, 7],
        [7, 9, 7, 2, 8]]])

In [20]:
x4[:, :2]

array([[[7, 1, 8, 1, 7],
        [6, 8, 5, 0, 8]],

       [[0, 1, 1, 5, 8],
        [8, 5, 2, 3, 5]]])

In [21]:
x4[:, 2:4, 1:3]

array([[[5, 6],
        [5, 0]],

       [[0, 9],
        [9, 7]]])

### Accessing array rows and columns

In [22]:
x4[:, 0]

array([[7, 1, 8, 1, 7],
       [0, 1, 1, 5, 8]])

In [23]:
x4[:, 1]

array([[6, 8, 5, 0, 8],
       [8, 5, 2, 3, 5]])

In [24]:
x4[:, 3]

array([[3, 5, 0, 6, 4],
       [7, 9, 7, 2, 8]])

# Function to multiply arrays

In [25]:
def mult(a, b):
    return np.dot(a, b)

In [26]:
mult([2, 4], [3, 5])

26

# Reshaping of Arrays

In [27]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
grid = grid.reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Concatenation and Splitting

In [29]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [30]:
z = [10, 20, 30]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 10, 20, 30])

In [31]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.concatenate(grid)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])