In [2]:
import numpy as np

# Generate random arrays

In [30]:
x1 = np.random.random((5,3))
x1

array([[0.21331198, 0.51820071, 0.02566272],
       [0.20747008, 0.42468547, 0.37416998],
       [0.46357542, 0.27762871, 0.58678435],
       [0.86385561, 0.11753186, 0.51737911],
       [0.13206811, 0.71685968, 0.3960597 ]])

In [33]:
x2 = np.random.randint(1000, size=30)
x2

array([305, 343, 542, 566, 153, 788, 353, 357, 697, 407, 411,  29, 929,
       371, 821, 631, 947, 854, 502,   7, 617, 137, 694, 896, 851, 376,
       932, 721, 148, 885])

In [36]:
x3 = np.random.randint(10, size=(2, 3, 4))
x3

array([[[5, 3, 6, 4],
        [7, 3, 0, 5],
        [9, 3, 7, 5]],

       [[5, 8, 0, 8],
        [3, 6, 9, 3],
        [2, 7, 0, 3]]])

### Print ndim, shape and size

In [43]:
print('x1 ndim:', x1.ndim, '| shape', x1.shape, '| size', x1.size)
print('x2 ndim:', x2.ndim, '| shape', x2.shape, '| size', x2.size)
print('x3 ndim:', x3.ndim, '| shape', x3.shape, '| size', x3.size)

x1 ndim: 2 | shape (5, 3) | size 15
x2 ndim: 1 | shape (30,) | size 30
x3 ndim: 3 | shape (2, 3, 4) | size 24


### Print itemsize and nbytes

In [47]:
print("itemsize:", x1.itemsize, "bytes")
print("itemsize:", x2.itemsize, "bytes")
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")
print("nbytes:", x2.nbytes, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
itemsize: 8 bytes
itemsize: 8 bytes
nbytes: 120 bytes
nbytes: 240 bytes
nbytes: 192 bytes


# Array Indexing

In [56]:
x = np.random.randint(10, size=5)
x

array([4, 9, 4, 1, 2])

In [57]:
x[1]

9

In [58]:
x[-1]

2

In [61]:
y = np.random.randint(10, size=(3, 4))
y

array([[0, 7, 6, 5],
       [9, 6, 5, 2],
       [7, 1, 9, 2]])

In [62]:
y[2, 0]

7

In [64]:
y[2, -2]

9

# Array Slicing

### One-dimensional subarrays

In [66]:
# x[start:stop:step]

In [68]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
x[:5]

array([0, 1, 2, 3, 4])

In [74]:
x[4:7]

array([4, 5, 6])

In [75]:
x[::2]

array([0, 2, 4, 6, 8])

In [76]:
x[1::2]

array([1, 3, 5, 7, 9])

### Multi-dimensional subarrays

In [128]:
x4 = np.random.randint(10, size=(2, 4, 5))
x4

array([[[5, 3, 2, 9, 9],
        [3, 2, 5, 4, 1],
        [5, 8, 3, 5, 8],
        [4, 1, 7, 8, 1]],

       [[2, 1, 1, 7, 5],
        [0, 4, 1, 1, 6],
        [6, 0, 2, 3, 7],
        [9, 2, 4, 9, 0]]])

In [129]:
x4[:, :2]

array([[[5, 3, 2, 9, 9],
        [3, 2, 5, 4, 1]],

       [[2, 1, 1, 7, 5],
        [0, 4, 1, 1, 6]]])

In [130]:
x4[:, 2:4, 1:3]

array([[[8, 3],
        [1, 7]],

       [[0, 2],
        [2, 4]]])

### Accessing array rows and columns

In [132]:
x4[:, 0]

array([[5, 3, 2, 9, 9],
       [2, 1, 1, 7, 5]])

In [140]:
x4[:, 1]

array([[3, 2, 5, 4, 1],
       [0, 4, 1, 1, 6]])

In [142]:
x4[:, 3]

array([[4, 1, 7, 8, 1],
       [9, 2, 4, 9, 0]])

# Function to multiply arrays

In [4]:
def mult(a, b):
    return np.dot(a, b)

In [144]:
mult([2, 4], [3, 5])

26

# Reshaping of Arrays

In [148]:
grid = np.arange(1, 10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [154]:
grid = grid.reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Array Concatenation and Splitting

In [156]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [157]:
z = [10, 20, 30]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 10, 20, 30])

In [158]:
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [160]:
np.concatenate(grid)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])